server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 106.15.39.106
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: model
          uri: lb://model-service
          predicates:
            - Path=/api/model/**
        - id: admin
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
        - id: merchant
          uri: lb://merchant-service
          predicates:
            - Path=/api/merchant/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
em:
  auth:
#    includePaths:
#      - /api/user/query
    excludePaths: # 无需登录校验的路径
      - /api/user/login
      - /api/user/verify
      - /api/user/register
      - /api/admin/login
      - /api/merchant/login
      - /api/user/forget-passwd